/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package jj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Type = 34;
  /** RegularExpression Id. */
  int BoolLiteral = 37;
  /** RegularExpression Id. */
  int CharLiteral = 38;
  /** RegularExpression Id. */
  int StringLiteral = 39;
  /** RegularExpression Id. */
  int IntegerLiteral = 40;
  /** RegularExpression Id. */
  int Identifier = 41;
  /** RegularExpression Id. */
  int Arrow = 42;
  /** RegularExpression Id. */
  int RegexBracket = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"|\"",
    "\"!\"",
    "\"^\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"[]\"",
    "\"[[\"",
    "\"]]\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"$\"",
    "\":\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "<Type>",
    "\"Set\"",
    "\"Map\"",
    "<BoolLiteral>",
    "<CharLiteral>",
    "<StringLiteral>",
    "<IntegerLiteral>",
    "<Identifier>",
    "<Arrow>",
    "\"\\u00a7\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 48>",
    "<token of kind 49>",
    "\"?\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
  };

}
