/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package jj;

import ast.ParamWrapper;
import ast.VariableType;
import ast.node.CuNode;
import ast.node.Node;
import ast.node.atom.*;
import ast.node.atom.literals.*;
import ast.node.decl.DeclNode;
import ast.node.decl.MethDeclNode;
import ast.node.decl.VarDeclNode;
import ast.node.expr.*;
import ast.node.stmnt.*;
import ast.node.type.ArrayTypeNode;
import ast.node.type.MapTypeNode;
import ast.node.type.SetTypeNode;
import ast.node.type.TypeNode;

public class Parser implements ParserConstants {

// Parser

// CU -> (decl | stmnt)*
  final public CuNode cu() throws ParseException {
    trace_call("cu");
    try {
CuNode node = new CuNode();
        Node declOrStmnt;
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:
        case 7:
        case 11:
        case 16:
        case 19:
        case 21:
        case 23:
        case 25:
        case 27:
        case 28:
        case 30:
        case 32:
        case 33:
        case Type:
        case 35:
        case 36:
        case BoolLiteral:
        case CharLiteral:
        case StringLiteral:
        case IntegerLiteral:
        case Identifier:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Type:
        case 35:
        case 36:{
          declOrStmnt = decl();
          break;
          }
        case 6:
        case 7:
        case 11:
        case 16:
        case 19:
        case 21:
        case 23:
        case 25:
        case 27:
        case 28:
        case 30:
        case 32:
        case 33:
        case BoolLiteral:
        case CharLiteral:
        case StringLiteral:
        case IntegerLiteral:
        case Identifier:{
          declOrStmnt = stmnt();
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
node.declOrStmntList.add(declOrStmnt);
      }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("cu");
    }
}

// decl -> type() <Identifier> (varDecl | methDecl | ";")
  final public DeclNode decl() throws ParseException {
    trace_call("decl");
    try {
Token identifier;
        TypeNode type;
        DeclNode node = null;
      type = type();
      identifier = jj_consume_token(Identifier);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 13:{
        node = varDecl(type, identifier);
        break;
        }
      case 21:{
        node = methDecl(type, identifier);
        break;
        }
      case 27:{
        jj_consume_token(27);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return node == null ? new DeclNode(type, identifier) : node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("decl");
    }
}

// varDecl -> "=" expr ";"
  final public VarDeclNode varDecl(TypeNode type, Token identifier) throws ParseException {
    trace_call("varDecl");
    try {
ExprNode expr;
      jj_consume_token(13);
      expr = expr();
      jj_consume_token(27);
{if ("" != null) return new VarDeclNode(type, identifier, expr);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("varDecl");
    }
}

// methDecl -> "(" (type <Identifier> ("," type <Identifier>)*)? ")" stmnt
  final public MethDeclNode methDecl(TypeNode type, Token identifier) throws ParseException {
    trace_call("methDecl");
    try {
MethDeclNode node = new MethDeclNode(type, identifier);
        TypeNode firstType, lastType;
        Token firstIdentifier, lastIdentifier;
        StmntNode body;
        int countIndex = 1;
      jj_consume_token(21);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Type:
      case 35:
      case 36:{
        firstType = type();
        firstIdentifier = jj_consume_token(Identifier);
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 14:{
            ;
            break;
            }
          default:
            jj_la1[3] = jj_gen;
            break label_2;
          }
          jj_consume_token(14);
          lastType = type();
          lastIdentifier = jj_consume_token(Identifier);
node.params.put(lastIdentifier, new ParamWrapper(countIndex++,lastType,lastIdentifier));
        }
node.params.put(firstIdentifier, new ParamWrapper(0,firstType,firstIdentifier));
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
      jj_consume_token(22);
      body = stmnt();
node.body = body; {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("methDecl");
    }
}

// stmnt -> returnStmnt | ifStmnt | whileStmnt | blockStmnt | expr | ";"
  final public StmntNode stmnt() throws ParseException {
    trace_call("stmnt");
    try {
StmntNode node = null;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 33:{
        node = returnStmnt();
        break;
        }
      case 30:{
        node = ifStmnt();
        break;
        }
      case 32:{
        node = whileStmnt();
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        if (jj_2_1(3)) {
          node = blockStmnt();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 6:
          case 7:
          case 11:
          case 16:
          case 19:
          case 21:
          case 23:
          case 25:
          case 28:
          case BoolLiteral:
          case CharLiteral:
          case StringLiteral:
          case IntegerLiteral:
          case Identifier:{
            node = expr();
            break;
            }
          case 27:{
            jj_consume_token(27);
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("stmnt");
    }
}

// returnStmnt -> "return" expr ";"
  final public ReturnStmntNode returnStmnt() throws ParseException {
    trace_call("returnStmnt");
    try {
ExprNode expr;
      jj_consume_token(33);
      expr = expr();
      jj_consume_token(27);
{if ("" != null) return new ReturnStmntNode(expr);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("returnStmnt");
    }
}

// ifStmnt -> "if" "(" expr ")" stmnt ("else" stmnt)?
  final public IfStmntNode ifStmnt() throws ParseException {
    trace_call("ifStmnt");
    try {
StmntNode ifExpr, ifStmnt, elseStmnt = null;
      jj_consume_token(30);
      jj_consume_token(21);
      ifExpr = expr();
      jj_consume_token(22);
      ifStmnt = stmnt();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 31:{
        jj_consume_token(31);
        elseStmnt = stmnt();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
{if ("" != null) return new IfStmntNode(ifExpr,ifStmnt,elseStmnt);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("ifStmnt");
    }
}

// whileStmnt -> "while" "(" expr ")" stmnt
  final public WhileStmntNode whileStmnt() throws ParseException {
    trace_call("whileStmnt");
    try {
StmntNode whileExpr, whileStmnt;
      jj_consume_token(32);
      jj_consume_token(21);
      whileExpr = expr();
      jj_consume_token(22);
      whileStmnt = stmnt();
{if ("" != null) return new WhileStmntNode(whileExpr,whileStmnt);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("whileStmnt");
    }
}

// blockStmnt -> "{" (decl | stmnt)* "}"
  final public BlockStmntNode blockStmnt() throws ParseException {
    trace_call("blockStmnt");
    try {
BlockStmntNode node = new BlockStmntNode();
        Node declOrStmnt;
      jj_consume_token(25);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:
        case 7:
        case 11:
        case 16:
        case 19:
        case 21:
        case 23:
        case 25:
        case 27:
        case 28:
        case 30:
        case 32:
        case 33:
        case Type:
        case 35:
        case 36:
        case BoolLiteral:
        case CharLiteral:
        case StringLiteral:
        case IntegerLiteral:
        case Identifier:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Type:
        case 35:
        case 36:{
          declOrStmnt = decl();
          break;
          }
        case 6:
        case 7:
        case 11:
        case 16:
        case 19:
        case 21:
        case 23:
        case 25:
        case 27:
        case 28:
        case 30:
        case 32:
        case 33:
        case BoolLiteral:
        case CharLiteral:
        case StringLiteral:
        case IntegerLiteral:
        case Identifier:{
          declOrStmnt = stmnt();
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
node.declOrStmntList.add(declOrStmnt);
      }
      jj_consume_token(26);
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("blockStmnt");
    }
}

// type -> arrayType | <Type> | setType | mapType
  final public TypeNode type() throws ParseException {
    trace_call("type");
    try {
TypeNode node = null;
        Token type = null;
      if (jj_2_2(2)) {
        node = arrayType();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case Type:{
          type = jj_consume_token(Type);
          break;
          }
        case 35:{
          node = setType();
          break;
          }
        case 36:{
          node = mapType();
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
if(type == null) {
            {if ("" != null) return node;}
        } else {
            {if ("" != null) return new TypeNode(VariableType.of(type.image));}
        }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("type");
    }
}

// setType -> "Set" "<" <Type> ">"
  final public SetTypeNode setType() throws ParseException {
    trace_call("setType");
    try {
Token type;
      jj_consume_token(35);
      jj_consume_token(23);
      type = jj_consume_token(Type);
      jj_consume_token(24);
{if ("" != null) return new SetTypeNode(VariableType.of(type.image));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("setType");
    }
}

// mapType -> "Map" "<" <Type> , <Type> ">"
  final public MapTypeNode mapType() throws ParseException {
    trace_call("mapType");
    try {
Token key,value;
      jj_consume_token(36);
      jj_consume_token(23);
      key = jj_consume_token(Type);
      jj_consume_token(14);
      value = jj_consume_token(Type);
      jj_consume_token(24);
{if ("" != null) return new MapTypeNode(VariableType.of(key.image),VariableType.of(value.image));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("mapType");
    }
}

// arrayType -> <Type> "[]"
  final public ArrayTypeNode arrayType() throws ParseException {
    trace_call("arrayType");
    try {
Token type;
      type = jj_consume_token(Type);
      jj_consume_token(18);
{if ("" != null) return new ArrayTypeNode(VariableType.of(type.image));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("arrayType");
    }
}

// atom -> "!" atom | <Character> | <String> | <Integer> | <Boolean>
//         | set | map | array
//         | range | fa
//         | (<Identifier> ".")? methCall
//         | (state | <Identifier> ("." <Identifier>)*) (transition)?
  final public AtomNode atom() throws ParseException {
    trace_call("atom");
    try {
Token token = null;
        Token attribute;
        AtomNode atom;
        MethCallNode methCall;
        StateLitNode state = null;
        TransitionLitNode transition = null;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:{
        jj_consume_token(11);
        atom = atom();
{if ("" != null) return new NegationNode(atom);}
        break;
        }
      case CharLiteral:{
        token = jj_consume_token(CharLiteral);
{if ("" != null) return new LitNode(token);}
        break;
        }
      case StringLiteral:{
        token = jj_consume_token(StringLiteral);
{if ("" != null) return new LitNode(token);}
        break;
        }
      case IntegerLiteral:{
        token = jj_consume_token(IntegerLiteral);
{if ("" != null) return new LitNode(token);}
        break;
        }
      case BoolLiteral:{
        token = jj_consume_token(BoolLiteral);
{if ("" != null) return new LitNode(token);}
        break;
        }
      case 25:{
        atom = set();
{if ("" != null) return atom;}
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        if (jj_2_5(3)) {
          atom = map();
{if ("" != null) return atom;}
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 19:{
            atom = array();
{if ("" != null) return atom;}
            break;
            }
          case 16:{
            atom = range();
{if ("" != null) return atom;}
            break;
            }
          case 23:{
            atom = fa();
{if ("" != null) return atom;}
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            if (jj_2_6(4)) {
              if (jj_2_3(2)) {
                token = jj_consume_token(Identifier);
                jj_consume_token(15);
              } else {
                ;
              }
              methCall = methCall();
{if ("" != null) return new ClassMethCallNode(token, methCall);}
            } else if (jj_2_7(2)) {
              token = jj_consume_token(Identifier);
              jj_consume_token(15);
              attribute = jj_consume_token(Identifier);
{if ("" != null) return new ReadClassAttributeNode(token, attribute);}
            } else {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case 28:
              case Identifier:{
                switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
                case 28:{
                  state = state();
                  break;
                  }
                case Identifier:{
                  token = jj_consume_token(Identifier);
                  break;
                  }
                default:
                  jj_la1[11] = jj_gen;
                  jj_consume_token(-1);
                  throw new ParseException();
                }
                if (jj_2_4(3)) {
                  transition = transition();
                } else {
                  ;
                }
if (transition == null) {
            if (token == null) {
                {if ("" != null) return state;}
            } else {
                {if ("" != null) return new IdentifierNode(token);}
            }
        } else {
            {if ("" != null) return new TransitionLitWithStartNode(token, state, transition);}
        }
                break;
                }
              default:
                jj_la1[14] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
            }
          }
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("atom");
    }
}

// set -> "{" atom ("," atom)* "}"
  final public SetLitNode set() throws ParseException {
    trace_call("set");
    try {
SetLitNode node = new SetLitNode();
        AtomNode first, last;
      jj_consume_token(25);
      first = atom();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 14:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_4;
        }
        jj_consume_token(14);
        last = atom();
node.elementList.add(last);
      }
node.elementList.add(first);
      jj_consume_token(26);
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("set");
    }
}

// map -> "[[" atom ":" atom ("," atom ":" atom)* "]]"
  final public MapLitNode map() throws ParseException {
    trace_call("map");
    try {
MapLitNode node = new MapLitNode();
        AtomNode firstKey, firstValue, lastKey, lastValue;
      jj_consume_token(19);
      firstKey = atom();
      jj_consume_token(29);
      firstValue = atom();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 14:{
          ;
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          break label_5;
        }
        jj_consume_token(14);
        lastKey = atom();
        jj_consume_token(29);
        lastValue = atom();
node.elements.put(lastKey, lastValue);
      }
node.elements.put(firstKey, firstValue);
      jj_consume_token(20);
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("map");
    }
}

// array -> "[[" atom ("," atom)* "]]"
  final public ArrayLitNode array() throws ParseException {
    trace_call("array");
    try {
ArrayLitNode node = new ArrayLitNode();
        AtomNode first, last;
      jj_consume_token(19);
      first = atom();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 14:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_6;
        }
        jj_consume_token(14);
        last = atom();
node.elementList.add(last);
      }
node.elementList.add(0, first);
      jj_consume_token(20);
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("array");
    }
}

// methCall -> <Identifier> "(" (atom ("," atom)*)? ")"
  final public MethCallNode methCall() throws ParseException {
    trace_call("methCall");
    try {
MethCallNode node = new MethCallNode();
        Token identifier;
        AtomNode first, last;
      identifier = jj_consume_token(Identifier);
      jj_consume_token(21);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 11:
      case 16:
      case 19:
      case 23:
      case 25:
      case 28:
      case BoolLiteral:
      case CharLiteral:
      case StringLiteral:
      case IntegerLiteral:
      case Identifier:{
        first = atom();
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 14:{
            ;
            break;
            }
          default:
            jj_la1[18] = jj_gen;
            break label_7;
          }
          jj_consume_token(14);
          last = atom();
node.elementList.add(last);
        }
node.elementList.add(0, first);
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(22);
node.identifier = identifier; {if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("methCall");
    }
}

// range -> "[" <Char> ("-" <Char)? ("," <Char> ("-" <Char)?)* "]" ("+" (range | <Identifier>))*
  final public RangeLitNode range() throws ParseException {
    trace_call("range");
    try {
RangeLitNode node = new RangeLitNode();
    RangeLitNode additionRange = null;
    Token additionIdentifier = null;
    Token a;
    Token b = null;
      jj_consume_token(16);
      a = jj_consume_token(CharLiteral);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 2:{
        jj_consume_token(2);
        b = jj_consume_token(CharLiteral);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        ;
      }
node.add(a, b); b=null;
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 14:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_8;
        }
        jj_consume_token(14);
        a = jj_consume_token(CharLiteral);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 2:{
          jj_consume_token(2);
          b = jj_consume_token(CharLiteral);
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          ;
        }
node.add(a, b); b=null;
      }
      jj_consume_token(17);
      label_9:
      while (true) {
        if (jj_2_8(2)) {
          ;
        } else {
          break label_9;
        }
        jj_consume_token(1);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 16:{
          additionRange = range();
          break;
          }
        case Identifier:{
          additionIdentifier = jj_consume_token(Identifier);
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
if(additionRange == null)
            node.add(additionIdentifier);
        else
            node.add(additionRange);
        additionRange = null;
        additionIdentifier = null;
      }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("range");
    }
}

// state -> "$" <String> ("^" (<Integer> | <Identifier>))?
  final public StateLitNode state() throws ParseException {
    trace_call("state");
    try {
Token label, accept = null;
      jj_consume_token(28);
      label = jj_consume_token(StringLiteral);
      if (jj_2_9(2)) {
        jj_consume_token(12);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IntegerLiteral:{
          accept = jj_consume_token(IntegerLiteral);
          break;
          }
        case Identifier:{
          accept = jj_consume_token(Identifier);
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } else {
        ;
      }
{if ("" != null) return new StateLitNode(label,accept);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("state");
    }
}

// transition -> (("-" "-" | "--") (range | <Identifier>) | "-") <Arrow> (state | <Identifier>)
  final public TransitionLitNode transition() throws ParseException {
    trace_call("transition");
    try {
Token rangeIdentifier = null;
        Token stateIdentifier = null;
        RangeLitNode range = null;
        StateLitNode state = null;
      if (jj_2_10(2)) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 2:{
          jj_consume_token(2);
          jj_consume_token(2);
          break;
          }
        case 7:{
          jj_consume_token(7);
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 16:{
          range = range();
          break;
          }
        case Identifier:{
          rangeIdentifier = jj_consume_token(Identifier);
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 2:{
          jj_consume_token(2);
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(Arrow);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        state = state();
        break;
        }
      case Identifier:{
        stateIdentifier = jj_consume_token(Identifier);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
{if ("" != null) return new TransitionLitNode(rangeIdentifier, stateIdentifier, range, state);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("transition");
    }
}

// TODO doku
// fa -> "<" (state | <Identifier>) ",{" (<Identifier> (transition)? ("," <Identifier (transition)?)*)? "}" ">"
  final public FaLitNode fa() throws ParseException {
    trace_call("fa");
    try {
FaLitNode node = new FaLitNode(null, null);
    StateLitNode state = null;
    TransitionLitNode transition = null;
    Token identifier = null;
    FaLitNode additionalFa = null;
      jj_consume_token(23);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 28:{
        state = state();
        break;
        }
      case Identifier:{
        identifier = jj_consume_token(Identifier);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
if(state == null)
            node.startStateIdentifier = identifier;
        else
            node.startState = state;
      jj_consume_token(14);
      jj_consume_token(25);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Identifier:{
        identifier = jj_consume_token(Identifier);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 2:
        case 7:{
          transition = transition();
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          ;
        }
node.add(identifier, transition); transition = null;
        label_10:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 14:{
            ;
            break;
            }
          default:
            jj_la1[31] = jj_gen;
            break label_10;
          }
          jj_consume_token(14);
          identifier = jj_consume_token(Identifier);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 2:
          case 7:{
            transition = transition();
            break;
            }
          default:
            jj_la1[32] = jj_gen;
            ;
          }
node.add(identifier, transition); transition = null;
        }
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        ;
      }
      jj_consume_token(26);
      jj_consume_token(24);
      label_11:
      while (true) {
        if (jj_2_11(2)) {
          ;
        } else {
          break label_11;
        }
        jj_consume_token(1);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 23:{
          additionalFa = fa();
          break;
          }
        case Identifier:{
          identifier = jj_consume_token(Identifier);
          break;
          }
        default:
          jj_la1[34] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
if(additionalFa == null)
            node.add(identifier);
        else
            node.add(additionalFa);
        additionalFa = null;
        identifier = null;
      }
{if ("" != null) return node;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("fa");
    }
}

// expr -> "(" expr ")" | compExpr (("&&" | "||") compExpr)?
  final public ExprNode expr() throws ParseException {
    trace_call("expr");
    try {
ExprNode node;
    CompExprNode a;
    CompExprNode b = null;
    Token op = null;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        jj_consume_token(21);
        node = expr();
        jj_consume_token(22);
{if ("" != null) return new BracketExpr(node);}
        break;
        }
      case 6:
      case 7:
      case 11:
      case 16:
      case 19:
      case 23:
      case 25:
      case 28:
      case BoolLiteral:
      case CharLiteral:
      case StringLiteral:
      case IntegerLiteral:
      case Identifier:{
        a = compExpr();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 8:
        case 9:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 8:{
            op = jj_consume_token(8);
            break;
            }
          case 9:{
            op = jj_consume_token(9);
            break;
            }
          default:
            jj_la1[35] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          b = compExpr();
          break;
          }
        default:
          jj_la1[36] = jj_gen;
          ;
        }
{if ("" != null) return new AndOrExpr(a, op, b);}
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr");
    }
}

// compExpr -> sumExpr (("=="|"!="|"<="|">="|"<"|">") sumExpr)?
  final public CompExprNode compExpr() throws ParseException {
    trace_call("compExpr");
    try {
SumExprNode a;
    SumExprNode b = null;
    Token op = null;
      a = sumExpr();
      if (jj_2_12(2)) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 50:{
          op = jj_consume_token(50);
          break;
          }
        case 51:{
          op = jj_consume_token(51);
          break;
          }
        case 52:{
          op = jj_consume_token(52);
          break;
          }
        case 53:{
          op = jj_consume_token(53);
          break;
          }
        case 23:{
          op = jj_consume_token(23);
          break;
          }
        case 24:{
          op = jj_consume_token(24);
          break;
          }
        default:
          jj_la1[38] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = sumExpr();
      } else {
        ;
      }
{if ("" != null) return new CompExprNode(a, op, b);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("compExpr");
    }
}

// sumExpr -> prodExpr (("+" | "-") prodExpr)?
  final public SumExprNode sumExpr() throws ParseException {
    trace_call("sumExpr");
    try {
ProdExprNode a;
    ProdExprNode b = null;
    Token op = null;
      a = prodExpr();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 1:
      case 2:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 1:{
          op = jj_consume_token(1);
          break;
          }
        case 2:{
          op = jj_consume_token(2);
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = prodExpr();
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
{if ("" != null) return new SumExprNode(a, op, b);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("sumExpr");
    }
}

// prodExpr -> intersectionExpr (("*" | "/") intersectionExpr)?
  final public ProdExprNode prodExpr() throws ParseException {
    trace_call("prodExpr");
    try {
IntersectionExprNode a;
    IntersectionExprNode b = null;
    Token op = null;
      a = intersectionExpr();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 3:
      case 4:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 3:{
          op = jj_consume_token(3);
          break;
          }
        case 4:{
          op = jj_consume_token(4);
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = intersectionExpr();
        break;
        }
      default:
        jj_la1[42] = jj_gen;
        ;
      }
{if ("" != null) return new ProdExprNode(a, op, b);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("prodExpr");
    }
}

// intersectionExpr -> preOrPostIncrementExpr ("^" preOrPostIncrementExpr)?
  final public IntersectionExprNode intersectionExpr() throws ParseException {
    trace_call("intersectionExpr");
    try {
PreOrPostIncrementExprNode a;
    PreOrPostIncrementExprNode b = null;
      a = preOrPostIncrementExpr();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 12:{
        jj_consume_token(12);
        b = preOrPostIncrementExpr();
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        ;
      }
{if ("" != null) return new IntersectionExprNode(a, b);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("intersectionExpr");
    }
}

// preOrPostIncrementExpr -> ("++" | "--") atom | atom ("++" | "--")?
  final public PreOrPostIncrementExprNode preOrPostIncrementExpr() throws ParseException {
    trace_call("preOrPostIncrementExpr");
    try {
AtomNode atom;
    Token op = null;
      if (jj_2_13(2)) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:{
          op = jj_consume_token(6);
          break;
          }
        case 7:{
          op = jj_consume_token(7);
          break;
          }
        default:
          jj_la1[44] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        atom = atom();
{if ("" != null) return new PreOrPostIncrementExprNode(atom, op, null);}
      } else if (jj_2_14(2)) {
        atom = atom();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 6:
        case 7:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case 6:{
            op = jj_consume_token(6);
            break;
            }
          case 7:{
            op = jj_consume_token(7);
            break;
            }
          default:
            jj_la1[45] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          ;
        }
{if ("" != null) return new PreOrPostIncrementExprNode(atom, null, op);}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("preOrPostIncrementExpr");
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_3R_atom_183_7_32()
 {
    if (jj_scan_token(StringLiteral)) return true;
    return false;
  }

  private boolean jj_3R_atom_182_7_31()
 {
    if (jj_scan_token(CharLiteral)) return true;
    return false;
  }

  private boolean jj_3R_atom_181_5_30()
 {
    if (jj_scan_token(11)) return true;
    if (jj_3R_atom_181_5_22()) return true;
    return false;
  }

  private boolean jj_3R_atom_181_5_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_atom_181_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_182_7_31()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_183_7_32()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_184_7_33()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_185_7_34()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_186_7_35()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_188_7_36()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_189_7_37()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_190_7_38()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_atom_193_7_39()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_prodExpr_347_29_70()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(3)) {
    jj_scanpos = xsp;
    if (jj_scan_token(4)) return true;
    }
    return false;
  }

  private boolean jj_3R_type_133_52_57()
 {
    if (jj_3R_setType_147_5_63()) return true;
    return false;
  }

  private boolean jj_3_14()
 {
    if (jj_3R_atom_181_5_22()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_preOrPostIncrementExpr_366_35_23()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) return true;
    }
    if (jj_3R_atom_181_5_22()) return true;
    return false;
  }

  private boolean jj_3R_preOrPostIncrementExpr_365_5_50()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) return true;
    }
    return false;
  }

  private boolean jj_3R_intersectionExpr_356_5_44()
 {
    if (jj_3R_preOrPostIncrementExpr_365_5_50()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_intersectionExpr_356_35_71()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_arrayType_164_5_13()
 {
    if (jj_scan_token(Type)) return true;
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_sumExpr_337_21_69()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(1)) {
    jj_scanpos = xsp;
    if (jj_scan_token(2)) return true;
    }
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_blockStmnt_124_5_12()) return true;
    return false;
  }

  private boolean jj_3R_prodExpr_347_5_29()
 {
    if (jj_3R_intersectionExpr_356_5_44()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_prodExpr_347_29_70()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_mapType_155_5_64()
 {
    if (jj_scan_token(36)) return true;
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3R_blockStmnt_124_34_41()
 {
    if (jj_3R_stmnt_91_5_49()) return true;
    return false;
  }

  private boolean jj_3_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) return true;
    }
    }
    }
    }
    }
    if (jj_3R_sumExpr_337_5_21()) return true;
    return false;
  }

  private boolean jj_3R_setType_147_5_63()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(23)) return true;
    return false;
  }

  private boolean jj_3R_sumExpr_337_5_21()
 {
    if (jj_3R_prodExpr_347_5_29()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_sumExpr_337_21_69()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_expr_318_23_68()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) return true;
    }
    return false;
  }

  private boolean jj_3R_compExpr_327_5_67()
 {
    if (jj_3R_sumExpr_337_5_21()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_arrayType_164_5_13()) return true;
    return false;
  }

  private boolean jj_3R_stmnt_91_48_55()
 {
    if (jj_3R_whileStmnt_115_5_61()) return true;
    return false;
  }

  private boolean jj_3R_type_133_5_52()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_3R_type_133_52_57()) {
    jj_scanpos = xsp;
    if (jj_3R_type_133_69_58()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_blockStmnt_124_11_40()
 {
    if (jj_3R_decl_61_5_48()) return true;
    return false;
  }

  private boolean jj_3R_expr_318_7_66()
 {
    if (jj_3R_compExpr_327_5_67()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_expr_318_23_68()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_blockStmnt_124_10_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_blockStmnt_124_11_40()) {
    jj_scanpos = xsp;
    if (jj_3R_blockStmnt_124_34_41()) return true;
    }
    return false;
  }

  private boolean jj_3R_fa_299_24_20()
 {
    if (jj_3R_fa_291_5_28()) return true;
    return false;
  }

  private boolean jj_3R_expr_317_5_62()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_expr_317_5_65()) {
    jj_scanpos = xsp;
    if (jj_3R_expr_318_7_66()) return true;
    }
    return false;
  }

  private boolean jj_3R_expr_317_5_65()
 {
    if (jj_scan_token(21)) return true;
    if (jj_3R_expr_317_5_62()) return true;
    return false;
  }

  private boolean jj_3R_blockStmnt_124_5_12()
 {
    if (jj_scan_token(25)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_blockStmnt_124_10_24()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_transition_278_38_19()
 {
    if (jj_3R_range_251_5_27()) return true;
    return false;
  }

  private boolean jj_3R_stmnt_91_29_54()
 {
    if (jj_3R_ifStmnt_107_5_60()) return true;
    return false;
  }

  private boolean jj_3R_whileStmnt_115_5_61()
 {
    if (jj_scan_token(32)) return true;
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3_11()
 {
    if (jj_scan_token(1)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fa_299_24_20()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_ifStmnt_107_5_60()
 {
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(21)) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_scan_token(12)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_fa_291_10_51()
 {
    if (jj_3R_state_267_5_42()) return true;
    return false;
  }

  private boolean jj_3R_transition_278_21_18()
 {
    if (jj_scan_token(2)) return true;
    if (jj_scan_token(2)) return true;
    return false;
  }

  private boolean jj_3R_fa_291_5_28()
 {
    if (jj_scan_token(23)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fa_291_10_51()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_returnStmnt_99_5_59()
 {
    if (jj_scan_token(33)) return true;
    if (jj_3R_expr_317_5_62()) return true;
    return false;
  }

  private boolean jj_3R_methCall_239_53_43()
 {
    if (jj_scan_token(14)) return true;
    return false;
  }

  private boolean jj_3R_stmnt_91_6_53()
 {
    if (jj_3R_returnStmnt_99_5_59()) return true;
    return false;
  }

  private boolean jj_3R_stmnt_91_5_49()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_stmnt_91_6_53()) {
    jj_scanpos = xsp;
    if (jj_3R_stmnt_91_29_54()) {
    jj_scanpos = xsp;
    if (jj_3R_stmnt_91_48_55()) {
    jj_scanpos = xsp;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_stmnt_91_105_56()) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_10()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_transition_278_21_18()) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_transition_278_38_19()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_transition_278_5_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_scan_token(2)) return true;
    }
    if (jj_scan_token(Arrow)) return true;
    xsp = jj_scanpos;
    if (jj_3R_transition_278_105_25()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_methCall_239_37_26()
 {
    if (jj_3R_atom_181_5_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_methCall_239_53_43()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_range_252_24_17()
 {
    if (jj_3R_range_251_5_27()) return true;
    return false;
  }

  private boolean jj_3R_state_267_5_42()
 {
    if (jj_scan_token(28)) return true;
    if (jj_scan_token(StringLiteral)) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_scan_token(1)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_range_252_24_17()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  private boolean jj_3R_decl_61_5_48()
 {
    if (jj_3R_type_133_5_52()) return true;
    if (jj_scan_token(Identifier)) return true;
    return false;
  }

  private boolean jj_3R_range_251_5_27()
 {
    if (jj_scan_token(16)) return true;
    if (jj_scan_token(CharLiteral)) return true;
    return false;
  }

  private boolean jj_3R_methCall_239_5_16()
 {
    if (jj_scan_token(Identifier)) return true;
    if (jj_scan_token(21)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_methCall_239_37_26()) jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_transition_278_5_14()) return true;
    return false;
  }

  private boolean jj_3R_array_229_5_46()
 {
    if (jj_scan_token(19)) return true;
    if (jj_3R_atom_181_5_22()) return true;
    return false;
  }

  private boolean jj_3R_map_220_5_15()
 {
    if (jj_scan_token(19)) return true;
    if (jj_3R_atom_181_5_22()) return true;
    if (jj_scan_token(29)) return true;
    return false;
  }

  private boolean jj_3R_set_211_5_45()
 {
    if (jj_scan_token(25)) return true;
    if (jj_3R_atom_181_5_22()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_scan_token(Identifier)) return true;
    if (jj_scan_token(15)) return true;
    return false;
  }

  private boolean jj_3R_preOrPostIncrementExpr_366_35_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) return true;
    }
    return false;
  }

  private boolean jj_3R_type_133_69_58()
 {
    if (jj_3R_mapType_155_5_64()) return true;
    return false;
  }

  private boolean jj_3R_atom_193_8_47()
 {
    if (jj_3R_state_267_5_42()) return true;
    return false;
  }

  private boolean jj_3R_intersectionExpr_356_35_71()
 {
    if (jj_scan_token(12)) return true;
    return false;
  }

  private boolean jj_3R_atom_193_7_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_atom_193_8_47()) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    xsp = jj_scanpos;
    if (jj_3_4()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_scan_token(Identifier)) return true;
    if (jj_scan_token(15)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    if (jj_3R_methCall_239_5_16()) return true;
    return false;
  }

  private boolean jj_3R_atom_190_7_38()
 {
    if (jj_3R_fa_291_5_28()) return true;
    return false;
  }

  private boolean jj_3R_atom_189_7_37()
 {
    if (jj_3R_range_251_5_27()) return true;
    return false;
  }

  private boolean jj_3R_stmnt_91_105_56()
 {
    if (jj_3R_expr_317_5_62()) return true;
    return false;
  }

  private boolean jj_3R_atom_188_7_36()
 {
    if (jj_3R_array_229_5_46()) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_map_220_5_15()) return true;
    return false;
  }

  private boolean jj_3R_atom_186_7_35()
 {
    if (jj_3R_set_211_5_45()) return true;
    return false;
  }

  private boolean jj_3R_atom_185_7_34()
 {
    if (jj_scan_token(BoolLiteral)) return true;
    return false;
  }

  private boolean jj_3R_transition_278_105_25()
 {
    if (jj_3R_state_267_5_42()) return true;
    return false;
  }

  private boolean jj_3R_atom_184_7_33()
 {
    if (jj_scan_token(IntegerLiteral)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[47];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x5aa908c0,0x5aa908c0,0x8202000,0x4000,0x0,0x40000000,0x1aa908c0,0x80000000,0x5aa908c0,0x5aa908c0,0x0,0x10000000,0x2000800,0x890000,0x10000000,0x4000,0x4000,0x4000,0x4000,0x12890800,0x4,0x4000,0x4,0x10000,0x0,0x84,0x10000,0x4,0x10000000,0x10000000,0x84,0x4000,0x84,0x0,0x800000,0x300,0x300,0x12a908c0,0x1800000,0x6,0x6,0x18,0x18,0x1000,0xc0,0xc0,0xc0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x5ff,0x5ff,0x0,0x0,0x1c,0x3,0x5e0,0x0,0x5ff,0x5ff,0x1c,0x400,0x1e0,0x0,0x400,0x0,0x0,0x0,0x0,0x5e0,0x0,0x0,0x0,0x400,0x500,0x0,0x400,0x0,0x400,0x400,0x0,0x0,0x0,0x400,0x400,0x0,0x0,0x5e0,0x3c0000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[14];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 47; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[54];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 47; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 54; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  private int trace_indent = 0;
/** Enable tracing. */
  final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
	 trace_enabled = false;
  }

  protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 14; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
