/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Type = 33;
  /** RegularExpression Id. */
  int BoolLiteral = 36;
  /** RegularExpression Id. */
  int CharLiteral = 37;
  /** RegularExpression Id. */
  int StringLiteral = 38;
  /** RegularExpression Id. */
  int IntegerLiteral = 39;
  /** RegularExpression Id. */
  int RegexLiteral = 40;
  /** RegularExpression Id. */
  int Identifier = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"|\"",
    "\"!\"",
    "\"^\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"[]\"",
    "\"[[\"",
    "\"]]\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"$\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "<Type>",
    "\"Set\"",
    "\"Map\"",
    "<BoolLiteral>",
    "<CharLiteral>",
    "<StringLiteral>",
    "<IntegerLiteral>",
    "<RegexLiteral>",
    "<Identifier>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 46>",
    "<token of kind 47>",
    "\"-->\"",
    "\"<$\"",
    "\",{\"",
    "\"}>\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
  };

}
