/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Type = 35;
  /** RegularExpression Id. */
  int Identifier = 38;
  /** RegularExpression Id. */
  int CharLiteral = 39;
  /** RegularExpression Id. */
  int StringLiteral = 40;
  /** RegularExpression Id. */
  int IntegerLiteral = 41;
  /** RegularExpression Id. */
  int DoubleLiteral = 42;
  /** RegularExpression Id. */
  int RegexLiteral = 43;
  /** RegularExpression Id. */
  int Comment = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"|\"",
    "\"!\"",
    "\"^\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"[]\"",
    "\"[[\"",
    "\"]]\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"$\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "<Type>",
    "\"Set\"",
    "\"Map\"",
    "<Identifier>",
    "<CharLiteral>",
    "<StringLiteral>",
    "<IntegerLiteral>",
    "<DoubleLiteral>",
    "<RegexLiteral>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Comment>",
    "\"Set<\"",
    "\"Map<\"",
    "\"-->\"",
    "\",{\"",
    "\"}>\"",
  };

}
